rails/spork2/config/routes.rb
Spork2::Application.routes.draw do
  resources :servings

end

rails/spork2/app/models/serving.rb
class Serving < ActiveRecord::Base
  # attr_accessible :title, :body
end

rails/spork2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

rails/spork2/app/controllers/servings_controller.rb
#encoding: ascii-8bit
class ServingsController < ApplicationController
  # GET /servings
  # GET /servings.json
  def index
	  q = 'name LIKE '
	  q2 = ' AND name LIKE '
	  keywords = params[:servsearch].to_s.split
	  if keywords.size > 0
	  		q = 'name LIKE ' + "'%#{keywords[0]}%'"
	  		keywords[1, keywords.size-1].each do |keyword|
	  			q = q + q2 + "'%#{keyword}%'"
			end
			@servings = Serving.all(:conditions => q)
	  else
	  		@servings = Serving.all
	  end
#	  p = '"%' + params[:servsearch].gsub(' ', '%", "%') + '%"'
#	  meth = Serving.method('where("' + q3 + '", ' + p + ')')
#	  @servings = meth.call
	  #@servings = Serving.where(q3, "%#{params[:servsearch]}%")	  
#	 	showedServings = showedServings.where("name LIKE ?", keyword)
#	 end
#	 @servings = showedServings

#	 @servings = Serving.where("name LIKE ?", "%#{params[:servsearch]}%")
    #@servings = Serving.name_like_all(params[:servsearch].to_s.split.ascend_by_name
#	 @search = Serving.search(:name_contains => params[:servsearch])
#	 @servings = @search.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @servings }
    end
  end

#  def preview
#  	 #@serving = Serving.find(params[:id])
#	 render :partial => 'preview', :content_type => 'text/html'
#  end
  # GET /servings/1
  # GET /servings/1.json
  def show
    @serving = Serving.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @serving }
    end
  end

  # GET /servings/new
  # GET /servings/new.json
  def new
    @serving = Serving.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @serving }
    end
  end

  # GET /servings/1/edit
  def edit
    @serving = Serving.find(params[:id])
  end

  # POST /servings
  # POST /servings.json
  def create
    @serving = Serving.new(params[:serving])

    respond_to do |format|
      if @serving.save
        format.html { redirect_to @serving, notice: 'Serving was successfully created.' }
        format.json { render json: @serving, status: :created, location: @serving }
      else
        format.html { render action: "new" }
        format.json { render json: @serving.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /servings/1
  # PUT /servings/1.json
  def update
    @serving = Serving.find(params[:id])

    respond_to do |format|
      if @serving.update_attributes(params[:serving])
        format.html { redirect_to @serving, notice: 'Serving was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @serving.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /servings/1
  # DELETE /servings/1.json
  def destroy
    @serving = Serving.find(params[:id])
    @serving.destroy

    respond_to do |format|
      format.html { redirect_to servings_url }
      format.json { head :no_content }
    end
  end
end

rails/spork2/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/spork2/app/helpers/servings_helper.rb
module ServingsHelper
end

rails/spork2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Spork2</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

rails/spork2/app/views/servings/_form.html.erb
<%= form_for(@serving) do |f| %>
  <% if @serving.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@serving.errors.count, "error") %> prohibited this serving from being saved:</h2>

      <ul>
      <% @serving.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails/spork2/app/views/servings/edit.html.erb
<h1>Editing serving</h1>

<%= render 'form' %>

<%= link_to 'Show', @serving %> |
<%= link_to 'Back', servings_path %>

rails/spork2/app/views/servings/index.html.erb
<script type='text/javascript' src='serving.js'></script>

<h1>Listing servings</h1>


<%= form_tag servings_path, :method => 'get' do %>
	<p>
		<%= text_field_tag :servsearch, params[:servsearch] %>
		<%= submit_tag "Search", :name => nil %>
	</p>
<% end %>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<%#= form_tag({:action => 'preview'}, :remote => true, :'data-update-target' => 'previewdiv') do %>
	<select name="foodselect" multiple size="30" multiple class="scrollmenu">
		<% @servings.each do |serving| %>
			<option> <%= serving.name %>
<!--  <tr>
    <td><%#= link_to serving.name + " (100g)", serving %></td>
    <td><%#=# link_to 'Edit', edit_serving_path(serving) %></td>
	 <td><%#=# link_to 'Destroy', serving, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
-->
		<% end %>
	<%#= submit_tag 'Info', :disable_with => 'Please Wait...' %>
<%# end %>
</table>

<br />

<div id="previewdiv">

</div>

<%= link_to 'New Serving', new_serving_path %>

rails/spork2/app/views/servings/new.html.erb
<h1>New serving</h1>

<%= render 'form' %>

<%= link_to 'Back', servings_path %>

rails/spork2/app/views/servings/show.html.erb
<p id="notice"><%= notice %></p>

<%= @serving.name %> (100g)</br>
<!--REMEMBER TO INCLUDE GROUP LATER!-->
kCal: <%= @serving.kcal %> kcal</br>
protein: <%= @serving.protein %> g</br>
carb: <%= @serving.carb %> g</br>
fat: <%= @serving.fat %> g</br> 
vitA: <%= @serving.vitA %> IU</br>
vitB1: <%= @serving.vitB1 %> mg</br>
vitB2: <%= @serving.vitB2 %> mg</br>
vitB3: <%= @serving.vitB3 %> mg</br>
vitB5: <%= @serving.vitB5 %> mg</br>
vitB6: <%= @serving.vitB6 %> mg</br>
vitB9: <%= @serving.vitB9 %> mcg</br>
vitB12: <%= @serving.vitB12 %> mcg</br>
vitC: <%= @serving.vitC %> mg</br>
vitD: <%= @serving.vitD %> mcg</br>
vitE: <%= @serving.vitE %> mg</br>
fiber: <%= @serving.fiber %> g</br>
potassium: <%= @serving.potassium %> mg</br>
calcium: <%= @serving.calcium %> mg</br>
phosphorus: <%= @serving.phosphorus %> mg</br>
magnesium: <%= @serving.magnesium %> mg</br>
manganese: <%= @serving.manganese %> mg</br>
iron: <%= @serving.iron %> mg</br>
sodium: <%= @serving.sodium %> mg</br>
copper: <%= @serving.copper %> mg</br>
zinc: <%= @serving.zinc %> mg</br>
selenium: <%= @serving.selenium %> mcg</br>
<!--fluoride: <%#= @serving.fluoride %></br>-->
<%#= link_to 'Edit', edit_serving_path(@serving) %> <!--|-->
<%#= link_to 'Back', servings_path %>